name: vitmarketplace
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: any
  provider: any
  google_fonts: any
  email_validator: ^2.1.17
  carousel_slider: any
  http: any
  url_strategy: ^0.2.0
  floating_snackbar: any
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: any
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "icon/icon.png"


flutter:
  uses-material-design: true
  assets:
    - assets/
    - icon/
